### ISSUE TITLE
Error when run example multiple instance on one machine

### ISSUE THREAD

**Issue by seaguest** [Scalingo/go-etcd-cron#9] opened 2021-09-07 06:22 UTC
Hello,

I run the example code in multiple instances (go run example.go under 3 terminals), then I gor the following error:
```
{"level":"warn","ts":"2021-09-07T14:18:51.008+0800","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0001ff180/#initially=[127.0.0.1:2379]","attempt":0,"error":"rpc error: code = Unknown desc = context deadline exceeded"}
2021/09/07 14:18:51 [etcd-cron] etcd error when handling 'test-v2' job: fail to lock mutex '': rpc error: code = Unknown desc = context deadline exceeded

```

```
package main

import (
	"context"
	"log"
	"os"
	"time"

	"github.com/Scalingo/go-etcd-cron"
)

func main() {
	log.Println("starting")
	cron, err := etcdcron.New()
	if err != nil {
		log.Fatal("fail to create etcd-cron", err)
	}
	cron.AddJob(etcdcron.Job{
		Name:   "test-v2",
		Rhythm: "* * * * * *",
		Func: func(ctx context.Context) error {
			log.Println("Every 1 seconds from", os.Getpid())
			return nil
		},
	})
	cron.Start(context.Background())
	time.Sleep(100 * time.Second)
	cron.Stop()
}

```

**Comment by Soulou** [comment] 2021-09-07 08:35
Hi there, thanks for your report, I try reproduce your issue:

![Screenshot from 2021-09-07 10-32-37](https://user-images.githubusercontent.com/329969/132312440-02f212da-652b-4468-82a7-eb5d700eb619.png)

Indeed there are some maybe unwanting warning for entities which are NOT executing the lock at some point. It is related to the timeout configuration of the session.

What you can see however is that each second only one instance gets the lock and execute the logics.

If you run only 2 instances for instance, you won't see those warning since there is never any timeout related to the lock (less contention on it since only 2 entites are disputing it)

**Comment by EtienneM** [comment] 2021-09-15 09:34
I'm closing it, please reopen with more information if you still think there is a bug in there

**Closed by EtienneM** 2021-09-15 09:34 UTC
